name: issues 

on: 
  workflow_call: 

jobs: 
  help-wanted: 
    if: github.event.label.name == 'help wanted'

    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Bedankt voor het aanmaken van dit ticket. 
            
            Omdat Sijot-Turnhout een scoutsvereniging is die gebruikmaakt van open-source software en onze focus ligt op het aanbieden van een jongerenwerking,
            rekenen we op de community om mee te helpen bij het diagnosticeren en oplossen van problemen. Het is voor ons niet haalbaar om elk probleem dat via GitHub wordt gemeld, zelf te onderzoeken en op te lossen.
            
            Dien, indien mogelijk, een pull-aanvraag in om het gemelde probleem op te lossen, bij voorkeur met bijbehorende tests. 
            Alle pull-requests worden zo snel mogelijk beoordeeld door het team van kernleden dat verantwoordelijk is voor het onderhoud van de open-source software die we binnen onze werking gebruiken.
            
            Bedankt alvast!
